default: &default
  adapter: postgresql
  encoding: unicode
  pool: 13

production:
  <<: *default
  database: greenroads_production

development:
  <<: *default
  database: greenroads_development

staging:
  <<: *default
  database: greenroads_staging

test:
  <<: *default
  database: greenroads_test


  
